//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashInAdvance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CashInAdvance()
        {
            this.CashInAdvanceApprovals = new HashSet<CashInAdvanceApproval>();
        }
    
        public int ID { get; set; }
        public int TravelExpenseID { get; set; }
        public string Reason { get; set; }
        public long RequiredCash { get; set; }
        public System.DateTime RequiredDate { get; set; }
        public System.DateTime ReturnedDate { get; set; }
        public string BeneficialName { get; set; }
        public string BankBranch { get; set; }
        public string AccountNo { get; set; }
        public string RequesterSignature { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsShown { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashInAdvanceApproval> CashInAdvanceApprovals { get; set; }
    }
}
