//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> ImageID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentID { get; set; }
        public string Position { get; set; }
        public string EmailAddress { get; set; }
        public string DivisionID { get; set; }
        public Nullable<int> LevelName { get; set; }
        public string GroupName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> FirstTimeLogin { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
    }
}
