//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseClaimDetail
    {
        public int ID { get; set; }
        public int ECID { get; set; }
        public int PaymentID { get; set; }
        public bool IsShown { get; set; }
    
        public virtual ExpenseClaim ExpenseClaim { get; set; }
        public virtual PaymentDetail PaymentDetail { get; set; }
    }
}
