//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentDetail()
        {
            this.ExpenseClaimDetails = new HashSet<ExpenseClaimDetail>();
        }
    
        public int ID { get; set; }
        public int PaymentID { get; set; }
        public int CostBudgetID { get; set; }
        public string Description { get; set; }
        public decimal ActualVND { get; set; }
        public decimal ActualUSD { get; set; }
        public bool IsShown { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseClaimDetail> ExpenseClaimDetails { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual TravelExpenseCostBudget TravelExpenseCostBudget { get; set; }
    }
}
