//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelExpenseApproval
    {
        public int ID { get; set; }
        public int TravelExpenseID { get; set; }
        public int ApprovalStep { get; set; }
        public string ApproverID { get; set; }
        public string ApproverName { get; set; }
        public string ApproverEmail { get; set; }
        public string ApproverPosition { get; set; }
        public string ApproverSignature { get; set; }
        public Nullable<System.DateTime> ApproverSignDate { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual TravelExpense TravelExpense { get; set; }
    }
}
