//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelExpenseCostBudget
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelExpenseCostBudget()
        {
            this.TravelExpenseCostDetails = new HashSet<TravelExpenseCostDetail>();
        }
    
        public int ID { get; set; }
        public int CostID { get; set; }
        public int BudgetID { get; set; }
        public Nullable<bool> IsShown { get; set; }
    
        public virtual TravelExpenseBudget TravelExpenseBudget { get; set; }
        public virtual TravelExpenseCost TravelExpenseCost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelExpenseCostDetail> TravelExpenseCostDetails { get; set; }
    }
}
