//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelExpenseEmployee
    {
        public int ID { get; set; }
        public int TravelExpenseID { get; set; }
        public string EmployeeCode { get; set; }
        public string FullName { get; set; }
        public string Position { get; set; }
        public string Division { get; set; }
        public string Department { get; set; }
        public bool IsShown { get; set; }
    
        public virtual TravelExpense TravelExpense { get; set; }
    }
}
