//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelExpenseCashInAdvance
    {
        public int ID { get; set; }
        public int TravelExpenseID { get; set; }
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Department { get; set; }
        public string Reason { get; set; }
        public int RequiredCash { get; set; }
        public System.DateTime RequiredDate { get; set; }
        public System.DateTime ReturnedDate { get; set; }
        public string BeneficialName { get; set; }
        public string BankBranch { get; set; }
        public string test { get; set; }
    }
}
