//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelExpense
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelExpense()
        {
            this.TravelExpenseApprovals = new HashSet<TravelExpenseApproval>();
            this.TravelExpenseAttachmentFiles = new HashSet<TravelExpenseAttachmentFile>();
            this.TravelExpenseEmployees = new HashSet<TravelExpenseEmployee>();
        }
    
        public int ID { get; set; }
        public int StatusID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public int TripDays { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string TripPurpose { get; set; }
        public long EstimatedCost { get; set; }
        public int ExchangeRate { get; set; }
        public string RequesterSignature { get; set; }
        public string TarNo { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsShown { get; set; }
    
        public virtual TravelExpenseStatu TravelExpenseStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelExpenseApproval> TravelExpenseApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelExpenseAttachmentFile> TravelExpenseAttachmentFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelExpenseEmployee> TravelExpenseEmployees { get; set; }
    }
}
