//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelExpenseCostDetail
    {
        public int ID { get; set; }
        public int TravelExpenseID { get; set; }
        public int CostBudgetID { get; set; }
        public int CostAmount { get; set; }
        public long BudgetAmountAtSubmit { get; set; }
        public long BudgetUsedAtSubmit { get; set; }
        public long BudgetRemainingAtSubmit { get; set; }
        public bool IsShown { get; set; }
    
        public virtual TravelExpenseCostBudget TravelExpenseCostBudget { get; set; }
    }
}
